FROM node:22-alpine AS build
WORKDIR /web
COPY frontend/package.json /web/package.json
RUN npm install
COPY frontend /web
RUN npm run build

FROM nginx:alpine
COPY --from=build /web/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
